version: "3.8"

services:
  app:
    build: .
    container_name: 2mon
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: 2mon-mongo
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
